image: node:10.15.3

pipelines:
  default:
    - step:
        name: Build frontend
        script:
          - cd frontend
          - mv .env.production .env
          - npm install
          - npm run build
          - mkdir -p ~/.ssh
          - cat ../production_known_hosts >> ~/.ssh/known_hosts
          - (umask  077 ; echo $SSH_KEY | base64 -di > ~/.ssh/id_rsa)
          - ssh -i ~/.ssh/id_rsa root@46.36.36.187 'cd /app/react-api/frontend/build && rm `ls -A | grep -v favicon.ico | grep -v .htaccess | grep -v manifest.json`'
          - scp -i ~/.ssh/id_rsa ./build/* root@46.36.36.187:/app/react-api/frontend/build/


