version: "2"
services:
 data_mysql:
  image: busybox
  volumes:
  - ./docker/mysql:/var/lib/mysql
  - ./backup:/backup
 slim:
  build:
   context: .
   dockerfile: docker/Dockerfile
  container_name: slim-web
  ports:
  - "8081:80"
  volumes:
  - ./:/var/www/html/
  - ./docker/000-default.conf:/etc/apache2/sites-available/000-default.conf
  links:
  - db:db
  env_file:
  - .env
#  networks:
#  - esnet
 db:
  image: mysql:5.7
  container_name: slim-db
  expose:
  - "3306"
  ports:
  - "33062:3306"
  volumes_from:
  - data_mysql
  environment:
  - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  - MYSQL_DATABASE=${DB_NAME}
#  - MYSQL_USER=${DB_USER}
 adminer:
  image: adminer
  container_name: slim-adminer
  ports:
  - "8080:8080"
  links:
  - db:db     
  environment:
  - ADMINER_DESIGN=nette

 nginx-proxy:
  build:
    context: .
    dockerfile: docker/Dockerfile-nginx-proxy
  container_name: nginx-proxy
  ports:
    - "80:80"
  volumes:
    - ./docker/nginx-proxy-default.conf:/etc/nginx/conf.d/default.conf

 react:
# jako image se pouzije Dockerfile
  build:
   context: .
   dockerfile: docker/Dockerfile
  container_name: react
  ports:
  - "81:80"
  volumes:
  - ./react/build:/var/www/html/public
  - ./docker/000-default.conf:/etc/apache2/sites-available/000-default.conf
