version: "3"
services:
 data_mysql:
  image: busybox
  volumes:
  - ./docker/mysql:/var/lib/mysql
  - ./backup:/backup

 slim:
  build:
   context: .
   dockerfile: docker/Dockerfile
  container_name: slim-web
  ports:
  - "8081:80"
  volumes:
  - ./:/var/www/html/
  - ./docker/000-default.conf:/etc/apache2/sites-available/000-default.conf
  links:
  - db:db
  env_file:
  - .env
 db:
  image: mysql:5.7
  container_name: slim-db
  expose:
  - "3306"
  ports:
  - "33062:3306"
  volumes:
  - ./docker/mysql:/var/lib/mysql
  - ./backup:/backup
  environment:
  - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  - MYSQL_DATABASE=${DB_NAME}
#  - MYSQL_USER=${DB_USER}
 adminer:
  image: adminer
  container_name: slim-adminer
  ports:
  - "8080:8080"
  links:
  - db:db     
  environment:
  - ADMINER_DESIGN=nette
 proxy:
# jako image se pouzije Dockerfile
  build:
   context: .
   dockerfile: docker/Dockerfile-proxy
  container_name: proxy
#  extra_hosts:
#  - "docker.localhost:172.17.0.1"
  ports:
  - "80:80"
  volumes:
  - ./docker/proxy-default.conf:/etc/apache2/sites-available/000-default.conf

 react:
  build:
   context: .
   dockerfile: docker/Dockerfile
  container_name: react
  ports:
  - "81:80"
  volumes:
  - ./react/build:/var/www/html/public
  - ./docker/000-default.conf:/etc/apache2/sites-available/000-default.conf

 node:
  build:
    context: .
    dockerfile: node/Dockerfile
  volumes:
  - ./node/src:/node
  working_dir: /node
  ports:
  - "3001:3000"
  - "9229:9229"
  command:
  - 'forever'
  - '-c'
  - 'nodemon --exitcrash'
  - './app.js'
  environment:
  - MYSQL_PASSWORD=${DB_PASSWORD}
  - MYSQL_DATABASE=${DB_NAME}
