version: "2"
services:
 data_mysql:
  image: busybox
  volumes:
  - ./mysql:/var/lib/mysql
 slim:
# jako image se pouzije Dockerfile
  build:
   context: .
  container_name: slim-web
  extra_hosts:
  - "docker.localhost:172.17.0.1"
  ports:
  - "8081:80"
#  dns:
#  - 10.12.3.250
#  - 10.2.1.250
#  - 10.13.6.250
#  - 8.8.8.8
  volumes:
  - /home/machacej/test/slim/src:/var/www/html/
  - ./000-default.conf:/etc/apache2/sites-available/000-default.conf 
  links:
  - db:db
  env_file:
  - .env
#  networks:
#  - esnet
 db:
  image: mysql:5.7
  container_name: slim-db
  expose:
  - "3306"
  ports:
  - "33062:3306"
  volumes_from:
  - data_mysql
  environment:
  - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  - MYSQL_DATABASE=${DB_NAME}
#  - MYSQL_USER=${DB_USER}
 adminer:
  image: adminer
  container_name: slim-adminer
  ports:
  - "8080:8080"
  links:
  - db:db     
  environment:
  - ADMINER_DESIGN=nette

# elasticsearch:
#  image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
#  container_name: elastic1
#  environment:
#  - cluster.name=docker-cluster
#  - bootstrap.memory_lock=true
#  - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#  ulimits:
#   memlock:
#    soft: -1
#    hard: -1
#  volumes:
#  - /usr/share/elasticsearch/data:/home/machacej/test/elastic/data
#  ports:
#   - 9200:9200
# elasticsearch2:
#  image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
#  container_name: elastic2
#  environment:
#  - cluster.name=docker-cluster
#  - bootstrap.memory_lock=true
#  - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#  - "discovery.zen.ping.unicast.hosts=elasticsearch"
#  ulimits:
#   memlock:
#    soft: -1
#    hard: -1
#  volumes:
#  - /usr/share/elasticsearch/data:/home/machacej/test/elastic/data
##    networks:
##      - esnet
##  networks:
##  - esnet
# cerebro:
#  build: 
#   context: .
#   dockerfile: Dockerfile-cerebro
#  container_name: cerebro
#  ports:
#  - "9000:9000"
#  networks:
#  - esnet
  
#networks:
#  esnet:
#    driver: bridge
